Add check for the minimal docker/-compose version
src-d/engine pull request #258
Opened 2019-10-18 11:52 UTC by smacker

Fix: #253

Signed-off-by: Maxim Sukharev <max@smacker.ru>

---

* [ ] I have updated the CHANGELOG file according to the conventions in [keepachangelog.com](https://keepachangelog.com)
* [ ] This PR contains changes that do not require a mention in the CHANGELOG file

2019-10-18 17:47 UTC, dpordomingo reviewed
Could you mention these min versions in our docs?
https://github.com/src-d/sourced-ce/blob/master/docs/quickstart/1-install-requirements.md

2019-10-22 15:13 UTC, se7entyse7en requested changes
Maybe a typo.

2019-10-22 15:13 UTC, se7entyse7en commented on cmd/sourced/compose/compose.go
> +func getDockerComposeVersions(bin string) (*semver.Version, error) {
Why plural?

2019-10-22 15:18 UTC, se7entyse7en commented
Regarding the documentation, I don't see it as strictly required, because the error would be very clear. But if you prefer it's ok.

2019-10-22 15:31 UTC, smacker commented on cmd/sourced/compose/compose.go
> +func getDockerComposeVersions(bin string) (*semver.Version, error) {
typo, thanks!

2019-10-22 15:34 UTC, smacker commented
Fixed.

2019-10-22 15:39 UTC, dpordomingo commented
Given that there're people installing the tool to work offline, I think it could be better if we list the known dependencies (as they're not obvious)

2019-10-22 16:05 UTC, se7entyse7en commented
> Given that there're people installing the tool to work offline

good point! I didn't think about it 👍

2019-10-22 16:05 UTC, se7entyse7en approved these changes

2019-10-22 16:10 UTC, smacker commented
Versions were mentioned in the docs, the code changes are approved. Merging.

2019-10-22 16:10 UTC, merged