Add sql subcommand for gitbase mysql client
src-d/engine pull request #45
Opened 2019-06-12 08:57 UTC by smacker

Signed-off-by: Maxim Sukharev <max@smacker.ru>

2019-06-12 11:27 UTC, carlosms requested changes
Missing docs, entry in changelog

2019-06-12 11:45 UTC, carlosms commented on cmd/sourced/cmd/sql.go
> +	Command `name:"sql" short-description:"Open a mysql client connected for gitbase" long-description:"Open a mysql client connected for gitbase"`
```suggestion
	Command `name:"sql" short-description:"Open a MySQL client connected to gitbase" long-description:"Open a MySQL client connected to gitbase"`
```

2019-06-12 13:43 UTC, carlosms commented
Will it work on windows?

2019-06-12 17:30 UTC, smacker commented
Thanks! Re-pushed with updated documentation.

It should work on windows. (at least `docker exec -it` worked as expected) I can test tomorrow.

2019-06-13 09:53 UTC, smacker commented
works as a charm (srcd was inited without repos):
<img width="1036" alt="Screenshot 2019-06-13 at 11 52 15" src="https://user-images.githubusercontent.com/406916/59423086-bec87400-8dd1-11e9-9999-3d3e3e0d6d1b.png">

2019-06-13 10:14 UTC, carlosms commented on CHANGELOG.md
> +- `sql`: Open a MySQL client connected for gitbase
```suggestion
- `sql`: Open a MySQL client connected to gitbase
```

2019-06-13 10:14 UTC, carlosms commented on README.md
> +Open a MySQL client connected for gitbase.
```suggestion
Open a MySQL client connected to gitbase.
```

2019-06-13 10:14 UTC, carlosms commented on cmd/sourced/cmd/sql.go
> +	Command `name:"sql" short-description:"Open a MySQL client connected for gitbase" long-description:"Open a MySQL client connected for gitbase"`
```suggestion
	Command `name:"sql" short-description:"Open a MySQL client connected to gitbase" long-description:"Open a MySQL client connected to gitbase"`
```

2019-06-13 10:14 UTC, carlosms approved these changes
:+1: after the for/to text change

2019-06-13 12:10 UTC, smacker commented
for/to changed

2019-06-13 12:11 UTC, merged